proxy-nginx:
    restart: always
    image: nutsllc/toybox-nginx:1.15.7-alpine
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "~/workspace/docker-blog/proxy/data/html:/usr/share/nginx/html"
        - "~/workspace/docker-blog/proxy/conf/conf.d:/etc/nginx/conf.d"
        - "~/workspace/docker-blog/proxy/conf/vhost.d:/etc/nginx/vhost.d"
        - "~/workspace/docker-blog/proxy/conf/certs:/etc/nginx/certs"
    log_driver: "json-file"
    log_opt:
        max-size: "3m"
        max-file: "7"
    environment:
        - TOYBOX_UID=1000
        - TOYBOX_GID=1000
    ports:
        - "80:80"
        - "443:443"

proxy-docker-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: proxy-docker-gen
    links:
        - proxy-nginx
    volumes_from:
        - proxy-nginx
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "~/workspace/docker-blog/proxy/conf/docker-gen.conf:/docker-gen.conf"
        - "~/workspace/docker-blog/proxy/conf/docker-gen-templates:/etc/docker-gen/templates"
    log_driver: "json-file"
    log_opt:
        max-size: "3m"
        max-file: "7"
    command: -config /docker-gen.conf

proxy-letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    links:
        - proxy-nginx
    volumes_from:
        - proxy-nginx
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "~/workspace/docker-blog/proxy/conf/certs:/etc/nginx/certs:rw"
    log_driver: "json-file"
    log_opt:
        max-size: "3m"
        max-file: "7"
    environment:
        - NGINX_DOCKER_GEN_CONTAINER=proxy-docker-gen
        #- ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
        - ACME_CA_URI=https://acme-v01.api.letsencrypt.org/directory
